spring:
  application:
    name: Trip Cost Calculator
  jackson:
    date-format: "dd-MM-yyyy HH:mm:ss"
    time-zone: UTC

server.port: 0

trip-cost-calculator:
  input: "${input:input/taps.csv}"
  output: "${output:output/trips.csv}"
  currency-symbol: $
  cost-mappings:
    - stops:
        - Stop1
        - Stop2
      cost: 3.25
    - stops:
        - Stop2
        - Stop3
      cost: 5.50
    - stops:
        - Stop1
        - Stop3
      cost: 7.30
