spring:
  application:
    name: Trip Cost Calculator

trip-cost-calculator:
  input: input/taps.csv
  output: output/trips.csv
  cost-mappings:
    - stops:
        - stop1
        - stop2
      cost: 3.25
    - stops:
        - stop2
        - stop3
      cost: 5.50
    - stops:
        - stop1
        - stop3
      cost: 7.30
